In [1]:
import numpy as np
import pandas as pd

Creating a DataFrame

In [3]:
data = {
    'Name': ['jphn', 'Anna','Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [4]:
df

    Name  Age      City  Salary
0   jphn   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [5]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

selection and indexing of columns

In [6]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [8]:
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [9]:
df2[['Name', 'City']]

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

creating a new columns

In [11]:
df2["Designation"] = ['Doctor', 'Emgineer', 'Doctor', 'Engineer']

In [12]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Emgineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

Removing Columns

In [19]:
df2.drop('Designation', axis = 1, inplace = True)

C:\Users\Vikas Gaur\AppData\Local\Temp\ipykernel_25092\3937795832.py:1: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df2.drop('Designation', axis = 1, inplace = True)

KeyError: "['Designation'] not found in axis"

In [16]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
# inplace

Selecting Rows

Selecting Subsets of Rows and columns

Conditional Selection